### ISSUE TITLE
I am In belgium, (fr-be) and he speak with deutch accent

### ISSUE THREAD

**Issue by PowaBanga** [coldfix/pidgin-tts#1]
All is in the title... I don't understand... why... Is it normal ?

**Comment by coldfix** [comment]
Since you closed this, I guess you already figured this out on your own. In the conversation window enter

```
/tts lang fr-be
```

Now that you mention it, it would probably be nice to set the default according to the current locale. I'll have to think about if this is easy to do.

Best regards,
Thomas

**Comment by PowaBanga** [comment]
yes, it should be fun.

Maybe can you use this  
`echo $LANG`
or

```
case $LANG in
    fr_BE.UTF-8 ) echo fr-be ; LANGUAGE=fr-be ;;
    fr_FR.UTF-8 ) echo fr-fr ; LANGUAGE=fr-fr ;; 
    [...]
esac
```

all people who want in his language can modify your git :-) and keep the default language and your system config for all language who are not added...

**Comment by coldfix** [comment]
I'll add something ;)

**Comment by coldfix** [comment]
When run for the first time (language not yet set), this plugin will now detect the language from the current locale, see d3b46c0.
